import React, { useState } from 'react';
import { api } from '../api/client';
import { ErrorBlock } from '../components/Common';
import { TextInput } from '../components/Forms';

export default function ReportsPage() {
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [err, setErr] = useState(null);
  const [downloading, setDownloading] = useState(false);

  const onExport = async () => {
    setErr(null); setDownloading(true);
    try {
      // Attempt to get a URL or a OK string; if backend returns file directly, fallback will open new tab
      const res = await api.reports.exportPdf({ from, to });
      if (typeof res === 'string') {
        // If backend returns a path or URL, try open
        const url = res.startsWith('http') ? res : `${(process.env.REACT_APP_API_BASE_URL || 'http://localhost:3001')}${res}`;
        window.open(url, '_blank', 'noopener,noreferrer');
      } else if (res?.url) {
        window.open(res.url, '_blank', 'noopener,noreferrer');
      } else {
        // As a generic option, build a download link to a conventional endpoint
        const url = `${(process.env.REACT_APP_API_BASE_URL || 'http://localhost:3001')}/reports/export?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`;
        window.open(url, '_blank', 'noopener,noreferrer');
      }
    } catch (e) {
      setErr(e);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="grid">
      <div className="section-title">Reports</div>
      <div className="card pad" style={{ display: 'grid', gap: 12, maxWidth: 520 }}>
        <TextInput label="From (optional)" type="date" value={from} onChange={setFrom} />
        <TextInput label="To (optional)" type="date" value={to} onChange={setTo} />
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn primary" onClick={onExport} disabled={downloading}>
            {downloading ? 'Exporting…' : 'Export PDF'}
          </button>
          <span className="muted">A PDF timesheet will be generated by the backend.</span>
        </div>
      </div>
      <ErrorBlock error={err} />
    </div>
  );
}
